### ISSUE TITLE
[Bug]: IOS HA App doesn‘t display delay

### ISSUE THREAD

**Issue by HBgotMeHere** [silviokennecke/ha-public-transport-connection-card#21]
### Plugin Version

2.0.0

### Home Assistant Version

2025.1.2

### Browser / User Agent

HA IOS App

### Public Transport Sensor Integration

hacs-hafas 

### Dashboard view type

Sections

### Card configuration

```yaml
type: custom:public-transport-connection-card 
themen: homeassistant
entity: sensor.city1_to_city2
depature_station: city1
arrival_station: city2
connections_attribute: connections 
Connection_properties:
  description: products
  depature_time: depature
  depature_delay: delay 
  arrival_time: arrival
  arrival_delay: delay_arrival
displayed_connections: 2
```

### Description of the issue

The Delay is visible in Firefox (Pc) but not on iOS devices. Neither the App or Safari are displaying the delay.
